AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Izabel"

Globals:
  Function:
    CodeUri: "../handlers/"
    Runtime: "python3.7"
    MemorySize: 128
    Timeout: 60
    Environment:
      Variables:
        ENVIRONMENT: "production"
        REGION: !Ref AWS::Region
        ACCOUNT_ID: !Ref AWS::AccountId
        EMAIL: "{{resolve:ssm:/izabel/mail:1}}"

Resources:
  # IAM
  ExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${AWS::StackName}-api-execution-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: "EventBus"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "events:PutEvents"
                Resource: "*"

  # API
  Api:
    Type: "AWS::Serverless::Api"
    Properties:
      StageName: "Prod"
      Cors:
        AllowHeaders: "'*'"
        AllowOrigin: "'izabelrnn.com.br'"

  SendMail:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-send-mail"
      Handler: "send_mail.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /message
            Method: post
